### PR TITLE
Darryl Yeo - Light Switches

### PR DESCRIPTION
**Pull request by darrylyeo**
Light Switches
Copyright © 2015 Darryl Yeo
http://darryl-yeo.com

Demo at http://darryl-yeo.com/project/light-switches/index.html

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Hey @darrylyeo , Could you squash these commits ?

**Comment by darrylyeo** [comment]
No problem, done!

**Comment by jigyasa-grover** [comment]
Cool !

**Comment by darrylyeo** [comment]
Thanks!

**Comment by jigyasa-grover** [comment]
:v:

**Pull request merged**
